call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

nmap <C-c><C-d> :r !date "+\%Y\%m\%d"<CR>
set tags=tags

set foldmethod=indent
set number
set autoindent
set viminfo='20,\"50
syntax on

filetype on
filetype plugin on
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set backspace=2
set smarttab
set showmatch
set hlsearch
set incsearch
" set cursorline
" set listchars=tab:▸\ ,eol:¬
" set list

autocmd FileType python call SetPython()
function! SetPython() 
    colorscheme elflord
    setlocal keywordprg=pydoc
    setlocal makeprg=python\ %   
    setlocal errorformat=%+G\ \ File\ \"%f\"\\,\ line\ %l\\,\ in\ %m
    nmap <C-c><C-c> :!pyflakes %
    nmap <C-c><C-t> :!nosetests %
    autocmd BufWritePre *.py %s/\s\+$//e
    abbreviate prd print "*** [DEBUG]
    abbreviate pdb import pdb; pdb.set_trace()
    highlight OverLength ctermbg=darkred ctermfg=white guibg=#592929
    match OverLength /\%81v.\+/
endfunction

" some goodies from https://github.com/nelstrom/dotfiles/blob/master/vimrc

" let mapleader = ","
" nmap <silent> <leader>l :set list!<CR>
" nmap <silent> <leader>w :set wrap!<CR>
" nmap <silent> <leader>s :set spell!<CR>
" nmap <silent> <leader>n :silent :nohlsearch<CR>


" windows switching
map <C-k> <C-W>k
map <C-j> <C-W>j
map <C-h> <C-W>h
map <C-l> <C-W>l

" tab switching
" map <D-S-]> gt
" map <D-S-[> gT
" map <D-1> 1gt
" map <D-2> 2gt
" map <D-3> 3gt
" map <D-4> 4gt
" map <D-5> 5gt
" map <D-6> 6gt
" map <D-7> 7gt
" map <D-8> 8gt
" map <D-9> 9gt
" map <D-0> :tablast<CR>

